package com.fuzhu.entity;

import java.util.Date;

/**
 * CfMessage generated by fuzhucheng
 */

public class CfMessage  {

	private Long id;

	private String acceptor;			///收短信人的号码

	private String acceptorname;		//收信人名（有很多权限控制在这里的，详情见具体业务或者博主以后的例子）

	private String type;		//短信类别

	private String title;		//短信标题（可不填，预留而已）

	private String context;		//短信内容

	private Date starttime;

	private Date endtime;

	private Date createtime;

	private Long createuserid;		//可作为外联user表的键
	
	private Integer recordstatus;		//预留：一个状态字段
	


	// Constructors

	/** default constructor */
	public CfMessage() {
	}

	/** minimal constructor */
	public CfMessage(Long id) {
		this.id = id;
	}

	/** full constructor */
	public CfMessage(Long id, String acceptor, String acceptorname, String type,
			String title, String context, Date starttime, Date endtime,
			Date createtime, Long createuserid) {
		this.id = id;
		this.acceptor = acceptor;
		this.acceptorname = acceptorname;
		this.type = type;
		this.title = title;
		this.context = context;
		this.starttime = starttime;
		this.endtime = endtime;
		this.createtime = createtime;
		this.createuserid = createuserid;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getAcceptor() {
		return this.acceptor;
	}

	public void setAcceptor(String acceptor) {
		this.acceptor = acceptor;
	}

	public String getAcceptorname() {
		return this.acceptorname;
	}

	public void setAcceptorname(String acceptorname) {
		this.acceptorname = acceptorname;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContext() {
		return this.context;
	}

	public void setContext(String context) {
		this.context = context;
	}

	public Date getStarttime() {
		return this.starttime;
	}

	public void setStarttime(Date starttime) {
		this.starttime = starttime;
	}

	public Date getEndtime() {
		return this.endtime;
	}

	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public Long getCreateuserid() {
		return this.createuserid;
	}

	public void setCreateuserid(Long createuserid) {
		this.createuserid = createuserid;
	}

	public Integer getRecordstatus() {
		return recordstatus;
	}

	public void setRecordstatus(Integer recordstatus) {
		this.recordstatus = recordstatus;
	}


}